name: Deploy TKIT Al-Ishlah
on:
  push:
    branches: [main]
    paths: ["tkitalishlah/**"]
  pull_request:
    branches: [main]
    paths: ["tkitalishlah/**"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tkitalishlah
    steps:
      # checkout
      - uses: actions/checkout@v4

      # install bun
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: tkitalishlah/.bun-version

      # install packages
      - run: bun install --frozen-lockfile

      # build and deploy
      - run: bun run build
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: tkitalishlah
